app = "clan-destiny-pop"
primary_region = "ewr"
console_command = "/bin/bash -l"

[mounts]
source = "pop_cache"
destination = "/var"
initial_size = "3gb"

[[services]]
internal_port = 1101
protocol = "tcp"
# set auto_stop_machines to off because min_machines_running
# is only honored in the primary region:
auto_stop_machines = "off"
min_machines_running = 2
  [[services.ports]]
  handlers = ["proxy_proto"]
  proxy_proto_options = { version = "v2" }
  port = 80

[[services]]
internal_port = 1102
protocol = "tcp"
auto_stop_machines = "off"
min_machines_running = 2
  [[services.ports]]
  handlers = ["proxy_proto"]
  proxy_proto_options = { version = "v2" }
  port = 443
  [[services.http_checks]]
  interval = 10000 # ms
  grace_period = "30s"
  timeout = 500 # ms
  method = "get"
  path = "/"
  protocol = "https"
  # check atelierpentosaurus.com since it's directly served from the pop:
  tls_server_name = "www.atelierpentosaurus.com"
  tls_skip_verify = false

[[services]]
internal_port = 41641
protocol = "udp"
auto_stop_machines = "off"
min_machines_running = 2
  [[services.ports]]
  port = 41641

[[vm]]
size = "shared-cpu-1x"
memory = "512m"
