app = "clan-destiny-pop"
primary_region = "ewr"
console_command = "/bin/bash -l"

[mounts]
source = "pop_cache"
destination = "/var"
initial_size = "3gb"

[[services]]
internal_port = 1101
protocol = "tcp"
# set auto_stop_machines to off because min_machines_running
# is only honored in the primary region:
auto_stop_machines = "off"
min_machines_running = 2
  [[services.ports]]
  handlers = ["proxy_proto"]
  proxy_proto_options = { version = "v2" }
  port = 80

[[services]]
internal_port = 1102
protocol = "tcp"
auto_stop_machines = "off"
min_machines_running = 2
  [[services.ports]]
  handlers = ["proxy_proto"]
  proxy_proto_options = { version = "v2" }
  port = 443
  [[services.machine_checks]]
  entrypoint = ["/bin/bash", "-c"]
  # Check atelierpentosaurus.com since it's directly served from the pop:
  command = [ "curl -s --haproxy-protocol --cacert /etc/ssl/certs/ca-bundle.crt --resolve atelierpentosaurus.com:1102:[$FLY_TEST_MACHINE_IP] --retry 10 --retry-delay 10 --retry-all-errors -H Host:atelierpentosaurus.com https://atelierpentosaurus.com:1102/" ]
  kill_timeout = "120s"

[[services]]
internal_port = 41641
protocol = "udp"
auto_stop_machines = "off"
min_machines_running = 2
  [[services.ports]]
  port = 41641

[[vm]]
size = "shared-cpu-2x"
memory = "512m"
